#!/usr/bin/env bash

set -euo pipefail

readonly BIN="${1-}"
readonly scriptDir=$(dirname $0)

if [ -z "$BIN" ] ; then
  echo "Usage: $0 <bin>" >&2
  exit 1;
fi

readonly tmpDir=/tmp/llvm-cbe-test-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p $tmpDir

function main
{
  runTest compile_ll_test cyclic_structures.ll
  runTest compile_ll_test string_literal.ll
  runTest compile_ll_test string_literal_2.ll
  runTest compile_ll_test struct_initializers.ll
  runTest execute_test    function.ll
  runTest compile_ll_test function_arguments.ll
  runTest compile_ll_test cyclic_pointers.ll
  runTest compile_ll_test byval_struct.ll
  runTest compile_ll_test attributes.ll
  runTest execute_test    byval_array.ll
  runTest execute_test    floats.ll
  runTest execute_test    flexible_arrays.ll
  runTest execute_c_test  helloworld.cpp
  runTest execute_c_test  helloworld2.cpp
  runTest execute_c_test  argv.cpp
  runTest execute_c_test  argv.cpp  arg1
}

function runTest
{
  echo "Test: $*"
  if ! "$@" ; then
    echo "Failure"
    return 1
  fi
}

function compile_ll_test
{
  if ! $BIN/llvm-cbe $scriptDir/$1 -o=$tmpDir/output.c ; then
    echo "C generation failed"
    return 1
  fi

  if ! gcc -w -O0 -c $tmpDir/output.c -o $tmpDir/output.o ; then
    echo "The resulting program isn't compilable"
    cat $tmpDir/output.c | sed "s/^/  /" | grep -n "" | sed "s/^/> /"
    return 1
  fi
}

function execute_test
{
  name=$(basename $1 .ll)

  if ! $BIN/llvm-cbe $scriptDir/$name.ll -o=$tmpDir/output.c ; then
    echo "C generation failed"
    return 1
  fi

  if ! gcc -w -O0 $tmpDir/output.c $scriptDir/$name.c -o $tmpDir/output.exe ; then
    echo "The resulting program isn't compilable" >&2
    cat $tmpDir/output.c | sed "s/^/  /" | grep -n "" | sed "s/^/> /"
    return 1
  fi

  if ! $tmpDir/output.exe ; then
    echo "The resulting program returns an error" >&2
    return 1
  fi
}

function execute_c_test
{
  name=$(basename $1 .cpp)
  
  if ! clang-4.0 -O0 -S -emit-llvm $scriptDir/$name.cpp -o $tmpDir/output.ll ; then
    echo "The resulting program isn't compilable" >&2
    return 1
  fi

  if ! $BIN/llvm-cbe $tmpDir/output.ll ; then
    echo "C generation failed"
    return 1
  fi

  if ! gcc -w -O0 -lstdc++ $tmpDir/output.cbe.c -o $tmpDir/output.exe ; then
    echo "The resulting program isn't compilable" >&2
    cat $tmpDir/output.cbe.c | sed "s/^/  /" | grep -n "" | sed "s/^/> /"
    return 1
  fi

  if [ $# -eq 1 ] ; then
    if ! $tmpDir/output.exe  ; then
      echo "The resulting program returns an error" >&2
      return 1
    fi
  fi
  if [ $# -eq 2 ] ; then
    if ! $tmpDir/output.exe $2; then
      echo "The resulting program returns an error" >&2
      return 1
    fi
  fi
}

main "$@"
